### PR TITLE
Calculator sample, demo and docs

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Hello, First of all, I would like to thank you for making this beautiful library :) 

I wrote my first "hello world" with it, a simple calculator, and I thought I would share it with you.

[Demo here](https://zaidajaj.neocities.org/html/arch-calc/index.html)

[Repo here](https://github.com/Zaid-Ajaj/Arch-Calculator)

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello,
looks really nice :)
I will merge when the new Fable-arch website is ready (should be this week-end :))

**Comment by Zaid-Ajaj** [comment]
Awesome!

**Comment by Zaid-Ajaj** [comment]
Added the calculator to the docs. I tried to be as detailed as possible when explaining what was going on. I chose not to use the code used to render the calculator but rather used the code that matched with the code in de samples folder so that people would not get confused by seeing different code when they download the sample. 

On the side note, when I pulled the docs site and opened it in Visual Studio, it did not pick up the references from `node_modules` after `npm install`. Neither did Visual Studio Code :( so I was writing my code with 100+ errors all over the place. It did compile fine but the errors wouldn't go away

**Comment by MangelMaxime** [comment]
Didn't test the code yet but it's look nice.

Just one remark when writing the documentation comments at the bottom of the sample file. You can use `FsharpBlock` identifier to let the application include your code directly from the app code.

I mean if you defined a block like that:

```fsharp
  /// [BeginBlock:Actions]
  type Actions =
    | Tick of DateTime
  /// [EndBlock]
```

Then you can insert it with ` [FsharpBlock:Actions]`.

This is made in order to always have the documentation up to date with the actual code executed in the sample. And also, make easier the maintenance.

You can see how it's applied [here](https://github.com/fable-compiler/fable-arch/blob/master/docs/src/Pages/Sample/Sample_Clock.fs#L75-L101)

**Comment by Zaid-Ajaj** [comment]
Thanks!
Yes that part of using `[FsharpBlock]` was clear but I deliberately chose not to include the code executed because it is different than the code in sample folder which would be really confusing for the readers the read some code and when they download it, they would see something else. It shouldn't be very significant to maintanance since this is not updated very often

**Comment by MangelMaxime** [comment]
Oh ok I didn't pay enough attention to see the differences. But if it's wanted no problem ^^. Then we could probably remove the useless block declaration.

I have some concern about your problem with the IDE support. If you use Visual Studio could you try to remove the .dll file from the references and add it again via Visual Studio. If it's working like that for you we should be able to see the diff via git and perhaps solve the problem from it.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime I did the following steps:
 - Removed references from WebApp.fsproj
 - Deleted `node_modules` directory
 - Fresh `npm install`
 - Added references again and error were gone :) 
 - `git add docs/src/WebApp.fsproj`
 - Result: "Nothing to commit,  working directory clean"

**Comment by MangelMaxime** [comment]
Yes I have the same problem between my personal computer and my work station...
There is something breaking VS but I don't know the reason.

Are you using VS 2015 community ?

**Comment by Zaid-Ajaj** [comment]
Yes I am using VS 2015 Community.

**Comment by MangelMaxime** [comment]
Thanks for you PR :)

I will update the docs site with it.

**Pull request merged**
