### PR TITLE
fix regular F# build (build.fsx)

### PR DESCRIPTION
**Pull request by rfrerebe**
Hello,

I am unsure if this is of any interest because everything is transpiled to JS with Fable

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I am not sure of what you did here.

Can you explain please :) ?

**Comment by rfrerebe** [comment]
Hello,

I found that this project was not building on Windows using FAKE build system (build.cmd and build.fsx).
Build.fsx needs a nuget package Npm.Js 
Change on paket.dependencies and paket.lock correspond to this.

Also in fsproj, F# version is currently 4.3.1.0, while some code are using List.last
https://github.com/fable-compiler/fable-arch/blob/cba5d5588fd7c607d5913a4cab26eee2ae84a5f0/src/Fable.Arch/Fable.Arch.DevTools.fs#L44
This is only availble in version 4.4.0.0.
It correspond to the change on Fable.Arch.fsproj

Personally I like to have both F# compilation and Fable compilation working on the same code source.

I haven't check but it should be possible to update build.fsx to use npm from PATH.
Would you prefer that ?

**Comment by MangelMaxime** [comment]
Oh ok, thanks for the explanation I will review your PR during next week :)

**Comment by MangelMaxime** [comment]
I take a look and confirm that we need this PR to fix build process if we go to use FAKE.
However, @alfonsogarciacaro started to include a `build.js` inside repo when updating to Fable-0.7 

I personnally think using `build.js` can be a good approach because people comming from JS world could understand it :).
Just need to think about the doc gen which relies actually over F# Formatting. I would like to explore building the doc using fable-arch.

**Comment by rfrerebe** [comment]
Hello Maxime,

I recently ran into an other project that didn't need this Npm.Js package :
https://github.com/dogwith1eye/HelloArchFableSuave/blob/master/paket.dependencies
https://github.com/dogwith1eye/HelloArchFableSuave/blob/master/paket.lock

I believe a more recent version of FAKE solves this issue by reusing a local npm.
Thus I updated the PR.

Here is what I did :
I pinned Suave on version 1.1.3 which is the latest before 2 (Version 2 brings a lots of dependencies).
I ran "paket update".
It updated  Fake and DotLiquid (I don't expect any impact)
I ran .\build.cmd on a clean repo and it did build as expected.
The change in fsproj is the same.

In my humble opinion using build.js could be a separate PR, as this is just used to fix the F# build on Windows.

Thanks for your time
Rémy

**Comment by MangelMaxime** [comment]
Thanks for your PR :)

**Pull request merged**
