### PR TITLE
Added startWithNode for virtual-dom renderer

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
In this PR we should also support `startWithNode` for React renderer too.

**Comment by Zaid-Ajaj** [comment]
Done! I was not sure if the React renderer would be affected because `withStartNode` operated on `AppSpecification` but after looking at the react sample I saw I was wrong :)

The travis-ci fails with this:
```
The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .
```

**Comment by MangelMaxime** [comment]
Thanks for added the React support.

Yes I just saw this error in the Travis logs...
I will need to take a look but it's really strange because I didn't change the Travis configuration. Perhaps there was an update of the container by the community.

**Comment by Zaid-Ajaj** [comment]
It is strange indeed, maybe @alfonsogarciacaro knows something about this (travis-ci failing)?

**Comment by alfonsogarciacaro** [comment]
I also had problems with Travis C# container in recent days, but it seems they've been solved. I just closed and reopened the PR to force a new build. Crossing fingers... :)

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro It worked :) Thanks a lot!!!

**Pull request merged**
