### PR TITLE
Upgrade to Fable 0.7

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
This compiles fable-arch with Fable 0.7 and updates the react sample. Notes:

- I'm using the `build.js` node script as with fable-powerpack and fable-react. But you can still use FAKE if you prefer.
- The lib is now compiled and referenced as a `dll` so the contents to be distributed are put in a folder named `npm`.
- I've simplified the configuration of the React sample and replaced Webpack with the now embedded Rollup.
- I'm putting all the dependencies in the root folder so they don't need to be installed individually for each sample, but you may prefer to do otherwhise.
- I've added a self-contained node static server in `samples/server` to run the samples with `npm start`.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
One question.
Didn't Fable had problem when using dll + inline function ? Or is it fixed solved now ?

**Comment by alfonsogarciacaro** [comment]
Ups, you're right, functions cannot be inlined in .dlls. I thought I removed the `inline` modifiers, sorry 😅 I'll fix that!

**Comment by MangelMaxime** [comment]
I think React code don't have ìnline` modifiers.
But we are inlining everything for VirtualDom. I don't remember what was the reason.

**Comment by alfonsogarciacaro** [comment]
It was me who actually added the `inline`s ;) Mainly for performance, as there's no need to pass generics for VDom

**Comment by MangelMaxime** [comment]
Ok, I don't have any idea if this would hurt that much the performance or no.
We will need to do some perf test to compare inline or not.
And if performance are good this could be nice to go for the DLL. Because this would mean easier usage in project I think.

**Comment by alfonsogarciacaro** [comment]
Hehe, I just noticed I did remove the `inline` modifiers indeed. Github is just not showing the diff for Fable.Arch.Html.fs because it's too big ;)

**Comment by MangelMaxime** [comment]
Some info:
1. I ported my professional project to `0.10.0-alpha.1` without problem. Just needed to reference the .dll file and not the source files. 👍 
2. I am waiting for https://github.com/fable-compiler/Fable/issues/592 in order to measure the performance gain or lost of not using `inline` modifiers.

**Comment by MangelMaxime** [comment]
Ok so I got the ui-perf results:

Fable + virtualdom: 0.10.0-alpha.1
  **6620 ms**
Fable + virtualdom: 0.9.12
  **6497 ms**

For comparaison:
React 15.1.0
  **5558 ms**

So we get a little loose in performance. But we have a smaller bundle file and it's start to have some importance when doing a real website. For mine I got 60-70ko less in a 800ko file.

Also, one of the biggest supposed performance lost we got in fable-arch is we use `createObj` to send DSL info to virtual-dom lib.

**Comment by MangelMaxime** [comment]
Hello @alfonsogarciacaro ,

I just added some documentation in Fable.Arch.App.fs
Could you please take a look ?

My questions:
- Are those kind of lines suffisant: https://github.com/fable-compiler/fable-arch/pull/49/commits/5f35d9899f57e546cc257366660e928e5089d710#diff-21f57f58a60902e535da4004995d5565R44
- Do you find the function definition clearer when typed like on this line: https://github.com/fable-compiler/fable-arch/pull/49/commits/5f35d9899f57e546cc257366660e928e5089d710#diff-21f57f58a60902e535da4004995d5565R129

Personnally I find the markdown documentation enough. After when I add the type to the function definition it can help understand but some how make it hard to read.
Perhaps we should go for multiline definition if allowed by F#.

I will wait your feedback before continuing the documentation work.

Of couse @mastoj you can give your opinion too :)

**Comment by mastoj** [comment]
Great work @mangelmaxime. This is probably something that needs continuous improvement. Everything looks good for me.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I would like to release the 0.10.0 of Fable-arch which include the support for Fable 0.7.0 plus some others little stuff and the new docs website.

However, I got an error when trying to build Fable.Arch on my computer.
```
C:\Users\Maxime\Workspace\Github\fable-compiler\fable-arch>node build.js
fable-compiler 0.7.35: Start compilation...
C:\Users\Maxime\Workspace\Github\fable-compiler\fable-arch\src\Fable.Arch\Fable.Arch.DevTools.fs(L235,16) : warning FSHARP: This construct is deprecated
Compiled Fable.Arch.Html.js at 11:55:38 PM
Compiled Fable.Arch.App.js at 11:55:38 PM
Compiled Fable.Arch.Virtualdom.js at 11:55:38 PM
Compiled Fable.Arch.DevTools.js at 11:55:39 PM
Compiled Fable.Arch.RouteParser.js at 11:55:39 PM
Error when invoking Emitter.Com (L40,15-L40,78): Method not found: 'Fable.AST.Fable.Expr Fable.AST.Fable.Util.makeNonGenTypeRef(Fable.AST.Fable.Type)'. (C:\Users\Maxime\Workspace\Github\fable-compiler\fable-arch\src\Fable.Arch\Fable.Arch.React.fs)
   at Fable.React.Internal.Emitter.Com(ICompiler _com, ApplyInfo i)
[ERROR] FABLE EXIT CODE: 1
```

But the build is passing on travis in this PR. Could you please try to take a look if you got this error you too ?

Also, travis is using Fake to build the library but I plan to remove the Fake/paket dependencies to use only the build.js file which is simple to use in my opinion. And as the new docs website doesn't rely on FSharp.Formatting it's not needed anymore.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Sorry for taking so long to reply.

About the documentation, great work! :clap: I think this helps a lot contributors. It's good to have a comment for the public functions, and also to have the signature with meaningful names for the arguments and the generic placeholders (with this most of the times it's not necessary to add a explanation about the arguments in the function description). About comments inside the body of the function, maybe they're not that necessary unless there's a piece of code a bit obscure.

About the build fail, sorry, that was a breaking change for AST emitters (fable-react has one of those) that I introduced in one of latest Fable versions by mistake 😞 Please update fable-compiler, fable-core and fable-react to the latest versions (0.8.0 for fable-react) and it should be fixed.

**Comment by MangelMaxime** [comment]
Thanks @alfonsogarciacaro 
It's working now with the dependencies updated :)

**Pull request merged**
